### PR TITLE
Small Refactoring

### PR DESCRIPTION
**Pull request by ralmsdeveloper**
Hello @SteffenMangold ,
I made a small refactor, I also updated the package.
I liked the project!

### CODE REVIEW

**Review by SteffenMangold — COMMENTED** [review]
Can you explain why you switch to XUnit testing?

**Comment by SteffenMangold** [comment]
@ralmsdeveloper First thanks :) I needed it in production and decided to make it public, so anybody can use it. Please feel free to work with me on it.

**Comment by ralmsdeveloper** [comment]
@SteffenMangold, Sorry for turning to xUnit and do not justify :)

In addition to ReSharper provide an integrated support to it, the methods are shorter, all open source projects which I'm involved in use xUnit.

I can not confirm now, but xUnit was the one that offered the best test support.

Having said that, feel free, we can keep xUnit from now on.

**Comment by SteffenMangold** [comment]
@ralmsdeveloper maybe we can keep both. I like MS Unit test for integrated live testing in VS.

**Comment by ralmsdeveloper** [comment]
@SteffenMangold Live test, works perfectly with xUnit!

So it is better to keep one or the other.

**Comment by ralmsdeveloper** [comment]
Forecast for merge?

I would like to attack other things.

**Pull request closed without merging**
